# -*- coding: utf-8 -*-
#
# CubeBraid SDK documentation build configuration file.
# Based on Sphinx documentation configuration.
#
# This file is executed with the current directory set to its
# containing directory.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.


import os
import sys
import time


# ============================================================================
# Path configuration
# ============================================================================

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here.
#
# If the directory is relative to the documentation root, use
# os.path.abspath() to make it absolute.

sys.path.append(os.path.abspath('./plugins'))


# ============================================================================
# Project information
# ============================================================================

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list:
#
# source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# The default role.
default_role = 'any'

# The language for content autogenerated by Sphinx.
# Refer to Sphinx documentation for supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# language = 'en'
# 文档界面语言
language = 'zh_CN'


# The name of the project.
project = 'CubeBraid SDK Documentation'

# The author of the project.
author = 'GrantLi'

# Copyright information.
copyright = '{}, {}'.format(time.strftime('%Y'), author)


# ============================================================================
# General configuration
# ============================================================================

# The version info for the project you're documenting.
#
# |version| and |release| can be used in the documentation.
# These values are intentionally kept simple because this project
# does not use ROS 2 distribution/version management.

# The short X.Y version.
version = '1.0'

# The full version, including alpha/beta/rc tags.
release = '1.0'


# The set of warnings to suppress.
#
# Ignore image.nonlocal_uri warnings because some SDK documentation
# may reference images from external or shared locations.
suppress_warnings = [
    'image.nonlocal_uri',
]


# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
#
# source/_internal holds reusable snippets that are pulled into pages
# with the ".. include::" directive; they are never rendered as standalone pages.

exclude_patterns = [
    '**/_*.rst',
    '_internal/**',
]


# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# ============================================================================
# Extensions
# ============================================================================

# Add any Sphinx extension module names here, as strings.
#
# Extensions coming with Sphinx use the "sphinx.ext.*" namespace.
# Third-party extensions can also be added here.

extensions = [
    # Sphinx official extensions
    # 'sphinx.ext.graphviz',
    'sphinx.ext.ifconfig',
    'sphinx.ext.intersphinx',

    # Code copy button
    'sphinx_copybutton',

    # Tabbed content
    'sphinx_tabs.tabs',

    # Read the Docs theme
    'sphinx_rtd_theme',

    # Mermaid diagram support
    'sphinxcontrib.mermaid',

    # Open Graph metadata
    'sphinxext.opengraph',
]


# ============================================================================
# Intersphinx configuration
# ============================================================================

# Intersphinx allows the SDK documentation to reference
# external Python documentation.

intersphinx_mapping = {
    'python': (
        'https://docs.python.org/3',
        None,
    ),
}


# ============================================================================
# sphinx-copybutton configuration
# ============================================================================

# Configure sphinx-copybutton to not copy the following lines
# in console code-blocks:
#
#   1. Prompt lines ($): '.linenos, .gp'
#   2. Command output lines: '.go'
#
# See:
# https://sphinx-copybutton.readthedocs.io/en/latest/use.html

copybutton_exclude = '.linenos, .gp, .go'


# ============================================================================
# HTML output
# ============================================================================

# The theme to use for HTML and HTML Help pages.
#
# See Sphinx documentation for a list of builtin themes.

html_theme = 'sphinx_rtd_theme'


# Theme configuration.
#
# collapse_navigation:
#     Whether navigation sections are collapsed.
#
# sticky_navigation:
#     Whether the navigation remains visible while scrolling.
#
# navigation_depth:
#     Maximum navigation depth shown in the sidebar.

html_theme_options = {
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': -1,
}


# ============================================================================
# GitHub configuration
# ============================================================================

# Configure GitHub information displayed by the documentation theme.

# html_context = {
#     'display_github': True,
#     'github_user': 'GJXS1980',
#     'github_repo': 'cubebraid_documentation',
#     'github_version': 'main',
# }

html_context = {
    # GitHub 仓库信息
    'display_github': True,
    'github_user': 'GJXS1980',
    'github_repo': 'cubebraid_documentation',
    'github_version': 'main',
    'github_url': 'https://github.com/GJXS1980/cubebraid_documentation/',
}


# ============================================================================
# Templates
# ============================================================================

# Paths that contain custom templates.

templates_path = [
    'source/_templates',
]


# ============================================================================
# Static files
# ============================================================================

# Add any paths that contain custom static files such as CSS or JavaScript.
#
# These files are copied after the builtin static files.
# A file with the same name can overwrite the builtin theme file.

html_static_path = [
    'source/_static',
]


# Drop any source link suffix.
html_sourcelink_suffix = ''


# Relative to html_static_path.
#
# custom.css is recommended for CubeBraid-specific styling.
html_css_files = [
    'custom.css',
]


# JavaScript files.
#
# Add SDK documentation-specific JavaScript here if required.
html_js_files = []


# Favicon.
#
# Put favicon.ico under:
#
# source/favicon.ico

html_favicon = 'favicon.ico'


# ============================================================================
# HTML Help output
# ============================================================================

# Output file base name for HTML help builder.

htmlhelp_basename = 'cubebraid_sdk_documentation'


# ============================================================================
# Site URL
# ============================================================================

# Base URL of the CubeBraid SDK documentation website.
#
# If you do not have a public domain yet, this can be changed later.
#
# For local builds, this value does not affect the local HTTP server.

html_baseurl = 'https://docs.cubebraid.com'


# ============================================================================
# Open Graph configuration
# ============================================================================

# Open Graph metadata is used when documentation pages
# are shared on websites and social media.

ogp_site_url = 'https://docs.cubebraid.com/'
ogp_site_name = 'CubeBraid SDK Documentation'


# Open Graph image.
#
# Put the image under:
#
# source/_static/logo.png
#
# If the image does not exist yet, this configuration can be removed
# temporarily.

ogp_image = '_static/logo.png'


# ============================================================================
# Sitemap configuration
# ============================================================================

# URL scheme used by the sitemap generator.
#
# Since CubeBraid SDK Documentation does not use ROS 2 multiversion
# documentation, the URL structure is kept simple.

sitemap_url_scheme = '{link}'


# ============================================================================
# SDK documentation configuration
# ============================================================================

# You can define custom SDK-related configuration values here.
#
# These values can be accessed from templates or custom extensions.
#
# Example:
#
# cubebraid_sdk_name = 'CubeBraid SDK'
# cubebraid_sdk_version = '1.0'


cubebraid_sdk_name = 'CubeBraid SDK'
cubebraid_sdk_version = '1.0'


# ============================================================================
# Custom setup
# ============================================================================

def setup(app):
    """
    Sphinx 扩展初始化函数。

    这里仅保留 CubeBraid SDK Documentation 所需要的基础配置，
    不再使用 ROS 2 documentation 中的多版本、发行版和重定向机制。
    """

    # 注册 SDK 相关配置参数
    app.add_config_value(
        'cubebraid_sdk_name',
        'CubeBraid SDK',
        'html'
    )

    app.add_config_value(
        'cubebraid_sdk_version',
        '1.0',
        'html'
    )

    return {
        'version': '1.0',
        'parallel_read_safe': True,
        'parallel_write_safe': True,
    }